---
- name: command | after | nvm
  become: yes
  become_user: "{{ username | default('root') }}"
  shell: "{{ item.command }}"
  args:
    "{{ item.args_param }}"
  with_items:
    - "{{ nvm_command_after }}"
  when:
    nvm_command_after is defined
  register: nvm_command_after_output

- name: command | after | output | nvm
  debug:
    msg:
      "{{ nvm_command_after_output }}"
