---
# required directory | vault
- name: required directory | vault
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ vault_required_directory }}"
  when: vault_required_directory is defined
