apiVersion: v1
kind: ConfigMap
metadata:
  name: openresty-vhost-conf
  namespace: demo
data:
  default.conf: |-
    # nginx.vh.default.conf  --  docker-openresty
    #
    # This file is installed to:
    #   `/etc/nginx/conf.d/default.conf`
    #
    # It tracks the `server` section of the upstream OpenResty's `nginx.conf`.
    #
    # This config (and any other configs in `etc/nginx/conf.d/`) is loaded by
    # default by the `include` directive in `/usr/local/openresty/nginx/conf/nginx.conf`.
    #
    # See https://github.com/openresty/docker-openresty/blob/master/README.md#nginx-config-files
    #


    server {
        listen       80 default_server;
        server_name  _;

        # listen       80;
        # server_name  localhost;


        #charset koi8-r;
        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/local/openresty/nginx/html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/openresty/nginx/html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           /usr/local/openresty/nginx/html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }
  demo.com.conf: |-
    upstream demo {
      server    10.0.0.1:80 fail_timeout=0;
      server    10.0.0.2:80 fail_timeout=0;
      server    10.0.0.3:80 fail_timeout=0;
    }

    server {
        listen                    80;
        server_name               demo.com
                                  www.demo.com
                                  ;

        server_tokens             off;
        root                      /dev/null;

        set_real_ip_from 130.211.0.0/22;
        set_real_ip_from 35.191.0.0/16;
        real_ip_header True-Client-IP;
        real_ip_recursive on;

        # Increase this if you want to upload larger attachments
        client_max_body_size      20m;

        # individual nginx logs for this vhost
        access_log       /dev/stdout;
        error_log        /dev/stderr;
        # access_log       /usr/local/openresty/nginx/logs/demo.com_access.log;
        # error_log        /usr/local/openresty/nginx/logs/demo.com_error.log;

        location / {
            proxy_read_timeout      300;
            proxy_connect_timeout   300;
            proxy_redirect          off;

            proxy_set_header        X-Forwarded-Proto $scheme;
            proxy_set_header        Host              $http_host;
            proxy_set_header        X-Real-IP         $remote_addr;
            proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header        X-Frame-Options   SAMEORIGIN;

            proxy_pass              http://demo;
        }
    }
