---
# required directory | linux_account
- name: required directory | linux_account
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items:
    - "{{ linux_account_required_directory }}"
  when: linux_account_required_directory is defined
