---
# required data | golang
- name: required data | golang
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ golang_required_data }}"
  when: golang_required_data is defined

# required data | template | golang
- name: required data | template | golang
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ golang_required_data_template }}"
  when: golang_required_data_template is defined
