---
# required directory | golang
- name: required directory | golang
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ golang_required_directory }}"
  when: golang_required_directory is defined
