---
- name: required package | before | docker
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ docker_required_package_before }}"
  when: docker_required_package_before is defined

- name: required package | docker
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ docker_required_package }}"
  when: docker_required_package is defined
