---
- name: required package | helm
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ helm_required_package }}"
  when: helm_required_package is defined
