---
etcd_conf:
# etcd.conf
- src: "{{ template_etcd_conf_conf }}"
  dest: "/etc/etcd/etcd.conf"
  owner: root
  group: root
  mode: "0644"
  info:
    # member
    member:
    # - ETCD_CORS=""
    - ETCD_DATA_DIR="/data/etcd/default.etcd"
    # - ETCD_WAL_DIR=""
    - ETCD_LISTEN_PEER_URLS="http://{{ ansible_default_ipv4.address }}:2380"
    - ETCD_LISTEN_CLIENT_URLS="http://{{ ansible_default_ipv4.address }}:2379,http://127.0.0.1:2379"
    # - ETCD_MAX_SNAPSHOTS="5"
    # - ETCD_MAX_WALS="5"
    - ETCD_NAME="etcd{{ groups[group_names[0]].index(inventory_hostname) + 1 }}"
    # - ETCD_SNAPSHOT_COUNT="100000"
    # - ETCD_HEARTBEAT_INTERVAL="100"
    # - ETCD_ELECTION_TIMEOUT="1000"
    # - ETCD_QUOTA_BACKEND_BYTES="0"
    # - ETCD_MAX_REQUEST_BYTES="1572864"
    # - ETCD_GRPC_KEEPALIVE_MIN_TIME="5s"
    # - ETCD_GRPC_KEEPALIVE_INTERVAL="2h0m0s"
    # - ETCD_GRPC_KEEPALIVE_TIMEOUT="20s"

    # - PEER_NAME={{ hostvars[inventory_hostname]['ansible_hostname'] }}
    # - PRIVATE_IP={{ ansible_default_ipv4.address }}

    # clustering
    clustering:
    - ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ ansible_default_ipv4.address }}:2380"
    - ETCD_ADVERTISE_CLIENT_URLS="http://{{ ansible_default_ipv4.address }}:2379"
    # - ETCD_DISCOVERY=""
    # - ETCD_DISCOVERY_FALLBACK="proxy"
    # - ETCD_DISCOVERY_PROXY=""
    # - ETCD_DISCOVERY_SRV=""
    - ETCD_INITIAL_CLUSTER="{% for i in groups[group_names[0]] %}etcd{{ loop.index }}=http://{{ hostvars[i]['ansible_hostname'] }}:2380{% if not loop.last %},{% endif %}{% endfor %}"
    - ETCD_INITIAL_CLUSTER_TOKEN=etcd-sit
    - ETCD_INITIAL_CLUSTER_STATE="new"
    # - ETCD_STRICT_RECONFIG_CHECK="true"
    # - ETCD_ENABLE_V2="true"

    # # proxy
    # proxy:
    # # - ETCD_PROXY="off"
    # # - ETCD_PROXY_FAILURE_WAIT="5000"
    # # - ETCD_PROXY_REFRESH_INTERVAL="30000"
    # # - ETCD_PROXY_DIAL_TIMEOUT="1000"
    # # - ETCD_PROXY_WRITE_TIMEOUT="5000"
    # # - ETCD_PROXY_READ_TIMEOUT="0"

    # # security
    # security:
    # - ETCD_CERT_FILE="/etc/etcd/tls/server.pem"
    # - ETCD_KEY_FILE="/etc/etcd/tls/server-key.pem"
    # - ETCD_CLIENT_CERT_AUTH="true"
    # - ETCD_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
    # - ETCD_AUTO_TLS="true"
    # - ETCD_PEER_CERT_FILE="/etc/etcd/tls/peer.pem"
    # - ETCD_PEER_KEY_FILE="/etc/etcd/tls/peer-key.pem"
    # - ETCD_PEER_CLIENT_CERT_AUTH="true"
    # - ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
    # - ETCD_PEER_AUTO_TLS="true"

    # # logging
    # logging:
    # # - ETCD_DEBUG="false"
    # # - ETCD_LOG_PACKAGE_LEVELS=""
    # # - ETCD_LOG_OUTPUT="default"

    # # unsafe
    # unsafe:
    # # - ETCD_FORCE_NEW_CLUSTER="false"

    # # version
    # version:
    # # - ETCD_VERSION="false"
    # # - ETCD_AUTO_COMPACTION_RETENTION="0"

    # # profiling
    # profiling:
    # # - ETCD_ENABLE_PPROF="false"
    # # - ETCD_METRICS="basic"

    # # auth
    # auth:
    # # - ETCD_AUTH_TOKEN="simple"
