---
service:
- name: postgresql-11
  daemon_reload: yes

required_directory_after:
- path: /etc/systemd/system/postgresql-11.service.d
  owner: root
  group: root
  mode: "0755"
- path: /data
  owner: "root"
  group: "root"
  mode: "0755"
- path: /var/lib/pgsql/11
  owner: "postgres"
  group: "postgres"
  mode: "0755"
- path: /data/pgsql
  owner: "postgres"
  group: "postgres"
  mode: "0700"
- path: /data/pgsql/11
  owner: "postgres"
  group: "postgres"
  mode: "0700"
- path: /data/pgsql/11/data
  owner: "postgres"
  group: "postgres"
  mode: "0700"

required_package_before:
- name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

required_package:
- name: postgresql11-11.6-2PGDG.rhel7.x86_64
- name: postgresql11-server-11.6-2PGDG.rhel7.x86_64
- name: postgresql11-contrib-11.6-2PGDG.rhel7.x86_64
- name: postgresql11-libs-11.6-2PGDG.rhel7.x86_64
- name: pg_pathman11-1.5.10-1.rhel7.x86_64
# - name: pg_pathman11-debuginfo-1.5.10-1.rhel7.x86_64

postgresql_conf:
# override.conf
- src: "{{ template_override_conf }}"
  dest: "/etc/systemd/system/postgresql-11.service.d/override.conf"
  owner: root
  group: root
  mode: "0644"
  info:
    Environment:
    - Environment=PGDATA=/data/pgsql/11/data/

command_after:
  - command: |
      export PG_DATA_ROOT=/data/pgsql/11/data
      [ "$(ls -A ${PG_DATA_ROOT})" ] && echo "${PG_DATA_ROOT} Not Empty" || /usr/pgsql-11/bin/postgresql-11-setup initdb
    args_param:
      executable: /bin/bash

conf_backup:
- src: /data/pgsql/11/data/pg_hba.conf
  dest: /data/pgsql/11/data/pg_hba.conf.orig
- src: /data/pgsql/11/data/pg_ident.conf
  dest: /data/pgsql/11/data/pg_ident.conf.orig
- src: /data/pgsql/11/data/postgresql.auto.conf
  dest: /data/pgsql/11/data/postgresql.auto.conf.orig
- src: /data/pgsql/11/data/postgresql.conf
  dest: /data/pgsql/11/data/postgresql.conf.orig
