---
# required data | adoptopenjdk
- name: required data | adoptopenjdk
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ adoptopenjdk_required_data }}"
  when: adoptopenjdk_required_data is defined

# required data | template | adoptopenjdk
- name: required data | template | adoptopenjdk
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ adoptopenjdk_required_data_template }}"
  when: adoptopenjdk_required_data_template is defined
