---
elasticsearch_conf_security_limit:
- domain: root
  limit_type: soft
  limit_item: nofile
  value: "200000"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: root
  limit_type: hard
  limit_item: nofile
  value: "200000"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: "*"
  limit_type: soft
  limit_item: nofile
  value: "200000"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: "*"
  limit_type: hard
  limit_item: nofile
  value: "200000"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: root
  limit_type: soft
  limit_item: nproc
  value: "102400"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: root
  limit_type: hard
  limit_item: nproc
  value: "102400"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: "*"
  limit_type: soft
  limit_item: nproc
  value: "102400"
  dest: "/etc/security/limits.d/elasticsearch.conf"
- domain: "*"
  limit_type: hard
  limit_item: nproc
  value: "102400"
  dest: "/etc/security/limits.d/elasticsearch.conf"
