---
elasticsearch_conf_sysctl_conf:
# memory
- name: kernel.shmmax
  value: "{{ (ansible_memtotal_mb * 1024 * 1024 * 0.9) | int }}"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: kernel.shmall
  value: "{{ (ansible_memtotal_mb * 1024 * 1024 * 0.9 / 4096) | int }}"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: kernel.msgmax
  value: "65536"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: kernel.msgmnb
  value: "65536"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: vm.swappiness
  value: "1"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: vm.max_map_count
  value: "262144"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
# netowrk
- name: net.core.rmem_max
  value: "33554432"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.core.wmem_max
  value: "33554432"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.core.somaxconn
  value: "65535"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv4.tcp_tw_reuse
  value: "0"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv4.tcp_tw_recycle
  value: "0"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv4.tcp_fin_timeout
  value: "5"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv4.tcp_keepalive_time
  value: "300"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.core.netdev_max_backlog
  value: "30000"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv4.ip_forward
  value: "0"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv4.icmp_echo_ignore_broadcasts
  value: "1"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
# disable ipv6
- name: net.ipv6.conf.all.disable_ipv6
  value: "1"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
- name: net.ipv6.conf.default.disable_ipv6
  value: "1"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
# filesystem
- name: fs.file-max
  value: "1000000"
  sysctl_set: yes
  sysctl_file: /etc/sysctl.d/elasticsearch.conf
  state: present
  reload: yes
