---
# required data | elasticsearch
- name: required data | elasticsearch
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ elasticsearch_required_data }}"
  when: elasticsearch_required_data is defined

# required data | template | elasticsearch
- name: required data | template | elasticsearch
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ elasticsearch_required_data_template }}"
  when: elasticsearch_required_data_template is defined
