---
- name: required package | elasticsearch
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    enablerepo: "{{ item.enablerepo | default(omit) }}"
  with_items:
    - "{{ elasticsearch_required_package }}"
  when: elasticsearch_required_package is defined
