---
# update security limit | kafka_manager_conf
- name: update security limit | kafka_manager_conf
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ kafka_manager_conf_security_limit }}"
  when: kafka_manager_conf_security_limit is defined
