---
# required directory | vault_conf
- name: required directory | vault_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ vault_conf_required_directory }}"
  when: vault_conf_required_directory is defined
