---
# required data | vault_conf
- name: required data | vault_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ vault_conf_required_data }}"
  when: vault_conf_required_data is defined

# required data | template | vault_conf
- name: required data | template | vault_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ vault_conf_required_data_template }}"
  when: vault_conf_required_data_template is defined
