---
- hosts: '{{ hn }}'
  gather_facts: no
  roles:
    - role: "{{ (playbook_dir + '/consul_template_conf') | replace('playbook', 'roles') }}"
      become: True
      become_user: root
      become_method: sudo
