---
kafka_manager_service:
- name: kafka_manager
  daemon_reload: yes

kafka_manager_required_package_before:
- name: "unzip"

kafka_manager_required_package:
- name: "java-11-openjdk-11.0.8.10-0.el7_8.x86_64"

kafka_manager_required_directory:
- path: /data
  owner: root
  group: root
  mode: "0755"
- path: /data/kafka_manager
  owner: kafka_manager
  group: kafka_manager
  mode: "0755"
- path: /data/kafka_manager/service
  owner: kafka_manager
  group: kafka_manager
  mode: "0755"

kafka_manager_required_data_before_download_local:
- url: "https://github.com/yahoo/CMAK/releases/download/3.0.0.5/cmak-3.0.0.5.zip"
  dest: "{{ role_path }}/files/cmak-3.0.0.5.zip"

kafka_manager_required_data:
- src: "{{ role_path }}/files/cmak-3.0.0.5.zip"
  dest: "/tmp/cmak-3.0.0.5.zip"
  owner: root
  group: root
  mode: "0644"

kafka_manager_required_data_after_template:
- src: "centos_7_x/kafka_manager.service.j2"
  dest: "/etc/systemd/system/kafka_manager.service"
  owner: root
  group: root
  mode: "0644"

kafka_manager_required_data_after_permission:
- dest: /data/kafka_manager/service/cmak-3.0.0.5
  owner: kafka_manager
  group: kafka_manager

kafka_manager_unarchive_data:
- src: /tmp/cmak-3.0.0.5.zip
  dest: /data/kafka_manager/service
  owner: kafka_manager
  group: kafka_manager
  remote_src: "yes"

# cleanup
kafka_manager_cleanup_local:
- path: "{{ role_path }}/files/cmak-3.0.0.5.zip"

kafka_manager_cleanup_remote:
- path: /tmp/cmak-3.0.0.5.zip

# environment
kafka_manager_environment:
  user: kafka_manager
  group: kafka_manager
  execstart: /data/kafka_manager/service/cmak-3.0.0.5/bin/cmak -Dconfig.file=/data/kafka_manager/service/cmak-3.0.0.5/conf/application.conf -java-home /usr/lib/jvm/java-11-openjdk-11.0.8.10-0.el7_8.x86_64 -Dhttp.port=9000
  workingdirectory: /data/kafka_manager/service/cmak-3.0.0.5
