---
- name: required package | lvm
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ lvm_required_package }}"
  when: lvm_required_package is defined
