---
# specific directory | linux_account
- name: specific directory | linux_account
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items:
    - "{{ linux_account_specific_directory }}"
  when: linux_account_specific_directory is defined
