---
# required directory | crontab_conf
- name: required directory | crontab_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ crontab_conf_required_directory }}"
  when: crontab_conf_required_directory is defined
