---
# set variables
- include_tasks: "{{ role_path }}/tasks/common/set_variables.yml"

# include variables
- include_tasks: "{{ role_path }}/tasks/common/include_variables.yml"

# required data | before
- include_tasks: "{{ role_path }}/tasks/common/required_data_before.yml"

# required directory
- include_tasks: "{{ role_path }}/tasks/common/required_directory.yml"

# required data
- include_tasks: "{{ role_path }}/tasks/common/required_data.yml"

# unarchive data
- include_tasks: "{{ role_path }}/tasks/common/unarchive_data.yml"

# systemd
- include_tasks: "{{ role_path }}/tasks/common/systemd.yml"

# cleanup
- include_tasks: "{{ role_path }}/tasks/common/cleanup.yml"
