---
# required directory | td_agent_conf
- name: required directory | td_agent_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ td_agent_conf_required_directory }}"
  when: td_agent_conf_required_directory is defined
