---
# required directory | docker
- name: required directory | docker
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ docker_required_directory }}"
  when: docker_required_directory is defined
