---
# update sysctl | kibana_conf
- name: update sysctl | kibana_conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ kibana_conf_sysctl_conf }}"
  when: kibana_conf_sysctl_conf is defined
