---
# update conf | template | kibana_conf
- name: update conf | template | kibana_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ kibana_conf }}"
  when: kibana_conf is defined
  notify:
    - systemd daemon-reload
    - restart kibana

# update conf | custom | kibana_conf
- name: update conf | custom | kibana_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ kibana_conf_custom }}"
  when: kibana_conf_custom is defined
  notify:
    - systemd daemon-reload
    - restart kibana
