---
# check distribution exist | pyenv
- name: check distribution exist | pyenv
  local_action: stat path="{{ role_path }}/tasks/distribution/{{ distribution }}/main.yml"
  register: distribution_path_stat

# set variables | pyenv
- name: set variables | pyenv
  set_fact:
    distribution_yml_path: "{{ role_path }}/tasks/distribution/{{ distribution }}/main.yml"
  when: distribution_path_stat.stat.exists == True

# include tasks distribution yaml if exist | pyenv
- include_tasks: "{{ distribution_yml_path | default(role_path + '/tasks/common/empty.yml') }}"
