---
# required data | pyenv
- name: required data | pyenv
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ pyenv_required_data }}"
  when: pyenv_required_data is defined

# required data | template | pyenv
- name: required data | template | pyenv
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ pyenv_required_data_template }}"
  when: pyenv_required_data_template is defined
