---
# update sysctl | pyenv
- name: update sysctl | pyenv
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ pyenv_sysctl_conf }}"
  when: pyenv_sysctl_conf is defined
