---
# required data | td_agent
- name: required data | td_agent
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ td_agent_required_data }}"
  when: td_agent_required_data is defined

# required data | template | td_agent
- name: required data | template | td_agent
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ td_agent_required_data_template }}"
  when: td_agent_required_data_template is defined
