---
jenkins_conf_credentials_custom_command:
- command: |
    export JENKINS_URL="http://{{ jenkins_user }}:{{ jenkins_api_token }}@{{ inventory_hostname }}:8080"

    curl -s -XPOST ${JENKINS_URL}/credentials/store/system/domain/_/createCredentials \
    --data-urlencode 'json={
      "": "0",
      "credentials": {
        "scope": "GLOBAL",
        "id": "git",
        "username": "git",
        "privateKeySource": {
          "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource",
          "privateKey": "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\nQyNTUxOQAAACAj9H1gp4ZgNdUPheUcW/TZbHDo8P6n2EMZSgtTWwI0gAAAAKjdvvu53b77\nuQAAAAtzc2gtZWQyNTUxOQAAACAj9H1gp4ZgNdUPheUcW/TZbHDo8P6n2EMZSgtTWwI0gA\nAAAEBxtUUjSEp44YXI5FCUzWQUuWz7n3ZhDVNFKGjRuye3QCP0fWCnhmA11Q+F5Rxb9Nls\ncOjw/qfYQxlKC1NbAjSAAAAAJWNoYXJsZXNoc3VAQ2hhcmxlc3MtTWFjQm9vay1Qcm8ubG\n9jYWw=\n-----END OPENSSH PRIVATE KEY-----\n"
        },
        "description": "git",
        "$class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
      }
    }'
  args_param:
    executable: /bin/bash

# docker-credentials
- command: |
    export JENKINS_URL="http://{{ jenkins_user }}:{{ jenkins_api_token }}@{{ inventory_hostname }}:8080"

    curl -X POST ${JENKINS_URL}/credentials/store/system/domain/_/createCredentials \
    --data-urlencode 'json={
      "": "0",
      "credentials": {
        "scope": "GLOBAL",
        "id": "docker-credentials",
        "username": "docker",
        "password": "password",
        "description": "docker-credentials",
        "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
      }
    }'
  args_param:
    executable: /bin/bash

# kubeconfig
- command: |
    export JENKINS_URL="http://{{ jenkins_user }}:{{ jenkins_api_token }}@{{ inventory_hostname }}:8080"

    curl -s -XPOST ${JENKINS_URL}/credentials/store/system/domain/_/createCredentials \
    -F secret=@{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/files/kubeconfig \
    -F 'json={
      "": "4",
      "credentials": {
        "scope": "GLOBAL",
        "file": "secret",
        "id": "kubeconfig",
        "description": "kubeconfig",
        "fileName": "kubeconfig",
        "$class": "org.jenkinsci.plugins.plaincredentials.impl.FileCredentialsImpl"
      }
    }'
  args_param:
    executable: /bin/bash

# ansible-vault
- command: |
    export JENKINS_URL="http://{{ jenkins_user }}:{{ jenkins_api_token }}@{{ inventory_hostname }}:8080"

    curl -s -XPOST ${JENKINS_URL}/credentials/store/system/domain/_/createCredentials \
    --data-urlencode 'json={
      "": "4",
      "credentials": {
        "scope": "GLOBAL",
        "id": "ansible-vault",
        "description": "ansible-vault",
        "secret": "sample",
        "$class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
      }
    }'
  args_param:
    executable: /bin/bash
