---
postgresql_conf:
- src: postgresql.conf.j2
  dest: /data/pgsql/11/data/postgresql.conf
  owner: postgres
  group: postgres
  mode: "0644"
  info:
    listen_addresses: '*'
    port: '5432'
    max_connections: '2000'
    ssl: 'on'
    shared_buffers: '32GB'
    huge_pages: 'try'
    temp_buffers: '8MB'
    work_mem: '8MB'
    maintenance_work_mem: '1GB'
    autovacuum_work_mem: '-1'
    max_stack_depth: '1MB'
    bgwriter_delay: '100ms'
    bgwriter_lru_maxpages: '1000'
    bgwriter_lru_multiplier: '10.0'
    effective_io_concurrency: '16'
    max_worker_processes: '36'
    max_parallel_maintenance_workers: '36'
    max_parallel_workers_per_gather: '36'
    parallel_leader_participation: 'on'
    max_parallel_workers: '36'
    wal_level: 'replica'
    fsync: 'on'
    synchronous_commit: 'off'
    full_page_writes: 'on'
    wal_log_hints: 'on'
    wal_writer_delay: '100ms'
    checkpoint_timeout: '5min'
    max_wal_size: '30GB'
    checkpoint_completion_target: '0.9'
    archive_mode: 'on'
    archive_command: 'test ! -f /backup/postgres/archive_wal/%f && cp -v %p /backup/postgres/archive_wal/%f'
    max_wal_senders: '10'
    wal_keep_segments: '1875'
    max_replication_slots: '1'
    track_commit_timestamp: 'on'
    hot_standby: 'on'
    max_standby_streaming_delay: '-1'
    hot_standby_feedback: 'on'
    enable_bitmapscan: 'on'
    enable_hashagg: 'on'
    enable_hashjoin: 'on'
    enable_indexscan: 'on'
    enable_indexonlyscan: 'on'
    enable_material: 'on'
    enable_mergejoin: 'on'
    enable_nestloop: 'on'
    enable_parallel_append: 'on'
    enable_seqscan: 'on'
    enable_sort: 'on'
    enable_tidscan: 'on'
    enable_partitionwise_join: 'on'
    enable_partitionwise_aggregate: 'on'
    enable_parallel_hash: 'on'
    enable_partition_pruning: 'on'
    seq_page_cost: '0.02'
    random_page_cost: '0.04'
    cpu_tuple_cost: '0.01'
    cpu_index_tuple_cost: '0.005'
    cpu_operator_cost: '0.0025'
    parallel_tuple_cost: '0.1'
    parallel_setup_cost: '1000.0'
    min_parallel_table_scan_size: '8MB'
    min_parallel_index_scan_size: '512kB'
    effective_cache_size: '64GB'
    geqo: 'on'
    geqo_threshold: '12'
    geqo_effort: '5'
    geqo_pool_size: '0'
    geqo_generations: '0'
    geqo_selection_bias: '2.0'
    geqo_seed: '0.0'
    default_statistics_target: '100'
    constraint_exclusion: 'partition'
    cursor_tuple_fraction: '0.1'
    from_collapse_limit: '8'
    join_collapse_limit: '8'
    log_filename: 'postgresql_%Y%m%d%H.log'
    log_rotation_age: '60'
    log_min_duration_statement: '1000'
    log_line_prefix: '< %m > [%p]: [%l-1] %h: %u@%d :'
    log_timezone: 'ROC'
    track_counts: 'on'
    autovacuum: 'on'
    autovacuum_vacuum_scale_factor: '0.2'
    autovacuum_analyze_scale_factor: '0.1'
    idle_in_transaction_session_timeout: '15000'
    timezone: 'ROC'
    shared_preload_libraries: 'pg_stat_statements'
    session_preload_libraries: 'auto_explain'
    custom:
    - 'pg_stat_statements.track=all'
    - 'auto_explain.log_min_duration = 1000'
    - 'auto_explain.log_analyze = on'
    - 'auto_explain.log_timing = on'
