---
jenkins_conf_required_directory:
- path: /data
  owner: root
  group: root
  mode: "0755"
- path: /data/jenkins
  owner: jenkins
  group: jenkins
  mode: "0755"
- path: /data/jenkins/bin
  owner: jenkins
  group: jenkins
  mode: "0755"
- path: /data/jenkins/dev
  owner: jenkins
  group: jenkins
  mode: "0755"
