---
# required data | jenkins
- name: required data | jenkins
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ jenkins_required_data }}"
  when: jenkins_required_data is defined

# required data | template | jenkins
- name: required data | template | jenkins
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ jenkins_required_data_template }}"
  when: jenkins_required_data_template is defined
