---
# update security limit | jenkins
- name: update security limit | jenkins
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ jenkins_security_limit }}"
  when: jenkins_security_limit is defined
