---
# update sysctl | jenkins
- name: update sysctl | jenkins
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ jenkins_sysctl_conf }}"
  when: jenkins_sysctl_conf is defined
