---
# check variables exist | postgresql_conf
- name: check variables exist | postgresql_conf
  local_action: stat path="{{ role_path }}/vars/{{ env }}/{{ env_group }}/{{ var_file_name }}.yml"
  register: vars_yml

# include variables if exist | postgresql_conf
- include_vars: "{{ role_path }}/vars/{{ env }}/{{ env_group }}/{{ var_file_name }}.yml"
  when: vars_yml.stat.exists == True
