---
# required directory | postgresql_conf
- name: required directory | postgresql_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ postgresql_conf_required_directory }}"
  when: postgresql_conf_required_directory is defined
