---
# postgresql.conf | postgresql_conf
- name: update postgresql.conf | postgresql_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ postgresql_conf }}"
  when: postgresql_conf is defined
  notify:
    - show restart message

# pg_hba.conf | postgresql_conf
- name: pg_hba.conf | postgresql_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ pg_hba_conf }}"
  when:
    - pg_hba_conf is defined
