---
- name: required package | nvm
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ nvm_required_package }}"
  when: nvm_required_package is defined
