---
# cleanup | local | kafka_manager
- name: cleanup | local | kafka_manager
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ kafka_manager_cleanup_local }}"
  when: kafka_manager_cleanup_local is defined
  run_once: true
  delegate_to: localhost

# cleanup | remote | kafka_manager
- name: cleanup | remote | kafka_manager
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ kafka_manager_cleanup_remote }}"
  when: kafka_manager_cleanup_remote is defined
