---
# check vars yml exist | kafka_manager
- name: check vars yml exist | kafka_manager
  local_action: stat path="{{ role_path }}/vars/{{ distribution }}/main.yml"
  register: vars_yml

# include vars yml if exist | kafka_manager
- include_vars: "{{ role_path }}/vars/{{ distribution }}/main.yml"
  when: vars_yml.stat.exists == True
