---
# required data | kafka_manager
- name: required data | kafka_manager
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ kafka_manager_required_data }}"
  when: kafka_manager_required_data is defined

# required data | template | kafka_manager
- name: required data | template | kafka_manager
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ kafka_manager_required_data_template }}"
  when: kafka_manager_required_data_template is defined
