---
# required directory | kafka_manager
- name: required directory | kafka_manager
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ kafka_manager_required_directory }}"
  when: kafka_manager_required_directory is defined
