---
- name: required package | cfssl
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ cfssl_required_package }}"
  when: cfssl_required_package is defined
