---
- hosts: '{{ hn }}'
  gather_facts: no
  roles:
    - role: "{{ (playbook_dir + '/postgresql_permission') | replace('playbook', 'roles') }}"
      become: True
      become_user: root
      become_method: sudo
