---
- name: required package | coredns
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ coredns_required_package }}"
  when: coredns_required_package is defined
