---
jenkins_service:
- name: jenkins
  daemon_reload: yes

# jenkins_required_directory:
# - path: /usr/java/openjdk11
#   owner: root
#   group: root
#   mode: "0755"

jenkins_required_data_before_download_local:
# - url: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz"
#   dest: "{{ role_path }}/files/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz"
- url: "https://pkg.jenkins.io/redhat/jenkins.repo"
  dest: "{{ role_path }}/files/jenkins.repo"

jenkins_required_data:
# - src: "{{ role_path }}/files/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz"
#   dest: "/tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz"
#   owner: root
#   group: root
#   mode: "0644"
- src: "{{ role_path }}/files/jenkins.repo"
  dest: "/etc/yum.repos.d/jenkins.repo"
  owner: root
  group: root
  mode: "0644"

jenkins_required_data_after:
- src: /etc/sysconfig/jenkins
  dest: /etc/sysconfig/jenkins.orig
  owner: root
  group: root
  mode: "0644"
  remote_src: yes
  force: no

# jenkins_unarchive_data:
# - src: /tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz
#   dest: /usr/java/openjdk11
#   owner: root
#   group: root
#   extra_opts:
#     - "--strip-components=1"
#   remote_src: "yes"

# # command | before
# jenkins_command_before:
# - command: |
#     sudo $(which update-alternatives) --install /usr/bin/java java /usr/java/openjdk11/bin/java 1
#   args_param:
#     executable: /bin/bash

# required package key
jenkins_required_package_key:
- key: https://pkg.jenkins.io/redhat/jenkins.io.key

# required package
jenkins_required_package:
- name: jenkins

# # cleanup
# jenkins_cleanup_local:
# - path: "{{ role_path }}/files/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz"
# - path: "{{ role_path }}/files/jenkins.repo"

# jenkins_cleanup_remote:
# - path: /tmp/OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz
