---
- name: credentials | jenkins_conf
  uri:
    method: "{{ item.method | default('POST') }}"
    url: "{{ item.url }}"
    user: "{{ jenkins_user }}"
    password: "{{ jenkins_api_token }}"
    force_basic_auth: "{{ item.force_basic_auth | default('yes') }}"
    body: "{{ item.body }}"
    body_format: "{{ item.body_format | default('raw') }}"
    status_code: "{{ item.status_code | default('200') }}"
  with_items:
    - "{{ jenkins_conf_credentials }}"
  when:
    - jenkins_conf_credentials is defined
    - jenkins_url is defined
    - jenkins_user is defined
    - jenkins_api_token is defined
  delegate_to: localhost
  tags:
    - credentials

- name: credentials | custom | command | jenkins_conf
  shell: "{{ item.command }}"
  args:
    "{{ item.args_param }}"
  with_items:
    - "{{ jenkins_conf_credentials_custom_command }}"
  when:
    jenkins_conf_credentials_custom_command is defined
  delegate_to: localhost
  tags:
    - credentials
