---
# check vars yml exist | jenkins_conf
- name: check vars yml exist | jenkins_conf
  local_action: stat path="{{ role_path }}/vars/{{ env }}/{{ env_group }}/{{ var_file_name }}.yml"
  register: vars_yml
  tags:
    - initial

# include vars yml if exist | jenkins_conf
- include_vars: "{{ role_path }}/vars/{{ env }}/{{ env_group }}/{{ var_file_name }}.yml"
  when: vars_yml.stat.exists == True
  tags:
    - initial
