---
# required data | jenkins_conf
- name: required data | jenkins_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ jenkins_conf_required_data }}"
  when: jenkins_conf_required_data is defined
  tags:
    - initial

# required data | template | jenkins_conf
- name: required data | template | jenkins_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ jenkins_conf_required_data_template }}"
  when: jenkins_conf_required_data_template is defined
  tags:
    - initial
