---
# set variables | jenkins_conf
- name: set variables | jenkins_conf
  set_fact:
    env: "{{ inventory_dir | dirname | basename }}"
    env_group: "{{ inventory_dir | basename }}"
    var_file_name: "{{ group_names[0] }}"
  tags:
    - initial
