---
# required data | node_exporter
- name: required data | node_exporter
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ node_exporter_required_data }}"
  when: node_exporter_required_data is defined

# required data | template | node_exporter
- name: required data | template | node_exporter
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ node_exporter_required_data_template }}"
  when: node_exporter_required_data_template is defined
