---
- name: required directory | node_exporter
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items:
    - "{{ node_exporter_required_directory }}"
  when: node_exporter_required_directory is defined
