---
# required data | elasticsearch_conf
- name: required data | elasticsearch_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ elasticsearch_conf_required_data }}"
  when: elasticsearch_conf_required_data is defined

# required data | template | elasticsearch_conf
- name: required data | template | elasticsearch_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ elasticsearch_conf_required_data_template }}"
  when: elasticsearch_conf_required_data_template is defined
