---
# update conf | template | elasticsearch_conf
- name: update conf | template | elasticsearch_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ elasticsearch_conf }}"
  when: elasticsearch_conf is defined
  notify:
    - systemd daemon-reload

# update conf | custom | elasticsearch_conf
- name: update conf | custom | elasticsearch_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ elasticsearch_conf_custom }}"
  when: elasticsearch_conf_custom is defined
  notify:
    - systemd daemon-reload
