---
specific_group:
- name: "{{ group_node_exporter }}"
  gid: "{{ gid_node_exporter }}"

specific_user:
- name: "{{ user_node_exporter }}"
  uid: "{{ uid_node_exporter }}"
  group: "{{ group_node_exporter }}"
  groups: ""
  home: "/data/{{ user_node_exporter }}"
  create_home: no
  shell: /sbin/nologin
