---
specific_group:
- name: "{{ group_redis_exporter }}"
  gid: "{{ gid_redis_exporter }}"

specific_user:
- name: "{{ user_redis_exporter }}"
  uid: "{{ uid_redis_exporter }}"
  group: "{{ group_redis_exporter }}"
  groups: ""
  home: "/data/{{ user_redis_exporter }}"
  create_home: "no"
  system: "yes"
  shell: /sbin/nologin
