---
- name: required package | etcd
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ etcd_required_package }}"
  when: etcd_required_package is defined
