---
# update sysctl | gvm
- name: update sysctl | gvm
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ gvm_sysctl_conf }}"
  when: gvm_sysctl_conf is defined
