---
- name: required command | after | etcd_conf
  become: True
  become_user: "{{ input_user | default('root') }}"
  become_method: sudo
  shell: "{{ item.command }}"
  args:
    "{{ item.args_param }}"
  with_items:
    - "{{ etcd_conf_command_after }}"
  when:
    etcd_conf_command_after is defined
  register: etcd_conf_command_after_output

- name: required command output | after | etcd_conf
  debug:
    msg:
      "{{ etcd_conf_command_after_output }}"
