---
# check variables exist
- name: check vars yml exist
  local_action: stat path="{{ role_path }}/vars/{{ env }}/{{ env_group }}/{{ var_file_name }}.yml"
  register: vars_yml

# include variables if exist
- include_vars: "{{ role_path }}/vars/{{ env }}/{{ env_group }}/{{ var_file_name }}.yml"
  when: vars_yml.stat.exists == True
