---
# required directory | etcd_conf
- name: required directory | etcd_conf
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state | default('directory') }}"
  with_items:
    - "{{ etcd_conf_required_directory }}"
  when: etcd_conf_required_directory is defined
