---
# update conf | etcd_conf
- name: update conf | etcd_conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ etcd_conf }}"
  when: etcd_conf is defined
#   notify:
#     - reload etcd

# update conf | custom | etcd_conf
- name: update conf | custom | etcd_conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ custom_etcd_conf }}"
  when: custom_etcd_conf is defined
#   notify:
#     - reload etcd
