---
kafka_conf_required_data_before_download_local:
- url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.13.0/jmx_prometheus_javaagent-0.13.0.jar
  dest: "{{ role_path }}/files/jmx_prometheus_javaagent-0.13.0.jar"
