---
- name: required package | kibana
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ kibana_required_package }}"
  when: kibana_required_package is defined
