---
td_agent_conf:
- src: pgsql.conf.j2
  dest: /etc/td-agent/config.d/pgsql.conf
  owner: root
  group: root
  mode: "0755"
  info:
    source:
      label: '@pgsql'
      tag: pgsql.change.type
      log_path: "/data/pgsql/11/data/log/postgresql_*.log"
      pos_file: "/var/log/td-agent/postgresql.log.pos"
      parse:
        grok_pattern: '{% raw %}^< (?<timestamp>(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9]) (2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9]).([0-9]+))(.*) > (?<pre_message>(.*))sample_(?<user_name>.*)@(?<db_name>.*) :LOG:  duration: (?<duration>([0-9]+\.*[0-9]*))(?<after_message>(.*)){% endraw %}'
        multiline_start_regexp: '{% raw %}/^< (-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9]) (2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9]).([0-9]+)(.*) >/{% endraw %}'
        time_key: timestamp
        time_format: '%Y-%m-%d %H:%M:%S.%N'
        keep_time_key: 'true'
    label:
      name: '@pgsql'
      filter:
      - id: pgsql.change.type
        info:
        - '@type parser'
        - 'key_name duration'
        - 'reserve_data true'
        - 'emit_invalid_record_to_error false'
        parse:
        - 'types duration:integer'
        - '@type regexp'
        - 'expression /^(?<duration>.*)$/'
      - id: pgsql.check.duration
        info:
        - '@type record_transformer'
        - 'enable_ruby true'
        record:
        - 'db_name ${record["db_name"]}'
        - "result ${record['duration'] > 10000 ? 'yes' : 'no'}"
        - 'content ${record["pre_message"]}sample_${record["user_name"]}@${record["db_name"]} :LOG: duration:  ${record["duration"]}${record["after_message"]}'
      - id: pgsql.final
        info:
        - '@type record_transformer'
        - 'remove_keys result, pre_message, after_message, user_name'
      match:
      - id: pgsql.change.type
        info:
        - '@type rewrite_tag_filter'
        rule:
        - 'key duration'
        - 'pattern /^(.*)$/'
        - 'tag pgsql.check.duration'
      - id: pgsql.check.duration
        info:
        - '@type rewrite_tag_filter'
        rule:
        - 'key result'
        - 'pattern /^yes$/'
        - 'tag pgsql.final'
      - id: pgsql.final
        info:
        - '@type copy'
        store:
        - info:
          - '@type elasticsearch'
          - 'hosts es01.sample.com:9200,es02.sample.com:9200,es03.sample.com:9200'
          - 'logstash_format true'
          - 'logstash_dateformat %Y.%m.%d'
          - 'logstash_prefix pgsql
          - 'request_timeout 15s'
          - 'reload_connections false'
          - 'reconnect_on_error true'
          - 'reload_on_failure true'
          buffer:
            id: tag
            info:
            - flush_interval 10s
            - flush_thread_count 2
        - info:
          - '@type relabel'
          - '@label @prometheus'

- src: override.conf.j2
  dest: /etc/systemd/system/td-agent.service.d/override.conf
  owner: root
  group: root
  mode: "0644"
  info:
    Service:
      User: root
      Group: root
