---
zookeeper_conf:
# zoo.cfg
- src: zoo.cfg-3.6.2.j2
  dest: /data/zookeeper/service/conf/zoo.cfg
  owner: zookeeper
  group: zookeeper
  mode: "0644"
  info:
    dataDir: /data/zookeeper/data
    dataLogDir: /data/zookeeper/datalog
    cluster: "true"

# myid
- src: myid.j2
  dest: /data/zookeeper/data/myid
  owner: zookeeper
  group: zookeeper
  mode: "0644"

# java.env
- src: java.env.j2
  dest: /data/zookeeper/service/conf/java.env
  owner: zookeeper
  group: zookeeper
  mode: "0644"
  info:
    jvmflags: "-Xmx2048m -Xms2048m"

# systemd
- src: zookeeper.service.j2
  dest: /etc/systemd/system/zookeeper.service
  owner: root
  group: root
  mode: "0644"
  info:
    user: zookeeper
    group: zookeeper
    execstart: /data/zookeeper/service/bin/zkServer.sh start
    execstop: /data/zookeeper/service/bin/zkServer.sh stop
    execreload: /data/zookeeper/service/bin/zkServer.sh restart
    workingdirectory: /data/zookeeper/service
    syslogidentifier: zookeeper
    pidfile: /data/zookeeper/data/zookeeper_server.pid
    environment:
      zoo_log_dir: /data/zookeeper/logs
