---
- name: postgresql database
  postgresql_db:
    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    owner: "{{ item.owner | default('postgres') }}"
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  run_once: yes
  with_items:
    - "{{ postgresql_database }}"
  when:
    postgresql_database is defined
