---
# set variables
- name: set variables
  set_fact:
    env: "{{ inventory_dir | dirname | basename }}"
    env_group: "{{ inventory_dir | basename }}"
    group_name: "{{ group_names[0] }}"
    var_file_name: "{{ group_names[0] }}"
