---
- hosts: '{{ hn }}'
  roles:
    - role: "{{ (playbook_dir + '/kibana_conf') | replace('playbook', 'roles') }}"
      gather_facts: no
      become: True
      become_user: root
      become_method: sudo
