---
- name: required package | golang
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ golang_required_package }}"
  when: golang_required_package is defined
