---
# set variables
- include_tasks: "{{ role_path }}/tasks/common/set_variables.yml"

# include variables
- include_tasks: "{{ role_path }}/tasks/common/include_variables.yml"

# include distribution
- include_tasks: "{{ role_path }}/tasks/common/include_distribution.yml"

# required directory | before
- include_tasks: "{{ role_path }}/tasks/common/required_directory_before.yml"

# required data
- include_tasks: "{{ role_path }}/tasks/common/required_data.yml"

# required package
- include_tasks: "{{ role_path }}/tasks/distribution/{{ distribution }}/required_package.yml"

# required directory | after
- include_tasks: "{{ role_path }}/tasks/common/required_directory_after.yml"

# update conf
- include_tasks: "{{ role_path }}/tasks/common/update_conf.yml"

# command | after
- include_tasks: "{{ role_path }}/tasks/common/command_after.yml"

# conf backup
- include_tasks: "{{ role_path }}/tasks/common/conf_backup.yml"

# systemd
- include_tasks: "{{ role_path }}/tasks/common/systemd.yml"
