---
# cleanup | local | coredns
- name: cleanup | local | coredns
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ coredns_cleanup_local }}"
  when: coredns_cleanup_local is defined
  run_once: true
  delegate_to: localhost

# cleanup | remote | coredns
- name: cleanup | remote | coredns
  become: True
  become_user: root
  become_method: sudo
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ coredns_cleanup_remote }}"
  when: coredns_cleanup_remote is defined
