---
# required data | coredns
- name: required data | coredns
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ coredns_required_data }}"
  when: coredns_required_data is defined

# required data | template | coredns
- name: required data | template | coredns
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ coredns_required_data_template }}"
  when: coredns_required_data_template is defined
