---
# update sysctl | coredns
- name: update sysctl | coredns
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ item.sysctl_set }}"
    sysctl_file: "{{ item.sysctl_file }}"
    state: "{{ item.state }}"
    reload: "{{ item.reload }}"
  with_items:
    - "{{ coredns_sysctl_conf }}"
  when: coredns_sysctl_conf is defined
