---
# update security limit | coredns
- name: update security limit | coredns
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ coredns_security_limit }}"
  when: coredns_security_limit is defined
