---
- name: required package | kafka_manager
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ kafka_manager_required_package }}"
  when: kafka_manager_required_package is defined
