---
# required directory | helm
- name: required directory | helm
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ helm_required_directory }}"
  when: helm_required_directory is defined
