---
# required data | helm
- name: required data | helm
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ helm_required_data }}"
  when: helm_required_data is defined

# required data | template | helm
- name: required data | template | helm
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ helm_required_data_template }}"
  when: helm_required_data_template is defined
