---
- name: required package | kustomize
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ kustomize_required_package }}"
  when: kustomize_required_package is defined
