---
- name: required package | before
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ required_package_before }}"
  when: required_package_before is defined

- name: required package
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ required_package_override | default(required_package) }}"
  when: required_package is defined
