---
# required data | kibana
- name: required data | kibana
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ kibana_required_data }}"
  when: kibana_required_data is defined

# required data | template | kibana
- name: required data | template | kibana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ kibana_required_data_template }}"
  when: kibana_required_data_template is defined
