---
# required directory | kibana
- name: required directory | kibana
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ kibana_required_directory }}"
  when: kibana_required_directory is defined
