---
# required directory | etcd
- name: required directory | etcd
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ etcd_required_directory }}"
  when: etcd_required_directory is defined
