---
- name: required package | gvm
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ gvm_required_package }}"
  when: gvm_required_package is defined
