---
# conf backup
- name: conf backup
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: "{{ item.remote_src | default('yes') }}"
    force: "{{ item.force | default('no') }}"
  with_items:
    - "{{ conf_backup }}"
