---
# check variables exist
- name: check vars yml exist
  local_action: stat path="{{ role_path }}/vars/main/{{ distribution }}/main.yml"
  register: vars_yml

# include variables if exist
- include_vars: "{{ role_path }}/vars/main/{{ distribution }}/main.yml"
  when: vars_yml.stat.exists == True
