---
# required directory | before
- name: required directory | before
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  with_items:
    - "{{ required_directory_before }}"
  when: required_directory_before is defined
