---
# set variables
- name: set variables
  set_fact:
    env: "{{ group_names[0] }}"
    roles_name: "{{ role_path|basename }}"
    distribution: "{{ ansible_distribution.lower() }}_{{ ansible_distribution_major_version }}_x"

# check distribution yaml exist
- name: check distribution yaml exist
  local_action: stat path="{{ role_path }}/tasks/distribution/{{ distribution }}/main.yml"
  register: distribution_path_stat

# set variables | check distribution yaml exist
- name: set variables | check distribution yaml exist
  set_fact:
    distribution_yml_path: "{{ role_path }}/tasks/distribution/{{ distribution }}/main.yml"
  when: distribution_path_stat.stat.exists == True
