---
# postgresql conf
- name: postgresql conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ postgresql_conf }}"
  when: postgresql_conf is defined

# postgresql conf | custom
- name: postgresql conf | custom
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ postgresql_conf_custom }}"
  when: postgresql_conf_custom is defined
