---
- name: required package | node_exporter
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ node_exporter_required_package }}"
  when: node_exporter_required_package is defined
