---
- name: required package | vault
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ vault_required_package }}"
  when: vault_required_package is defined
