---
# required data | cfssl
- name: required data | cfssl
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ cfssl_required_data }}"
  when: cfssl_required_data is defined

# required data | template | cfssl
- name: required data | template | cfssl
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - "{{ cfssl_required_data_template }}"
  when: cfssl_required_data_template is defined
